### ISSUE TITLE
Need PT Online application needed in Version Keeper

### ISSUE THREAD

**Issue by maciejkowal** [adamgeorgeson/versionkeeper#7]
Hi,
We are working on PT Online (Personal Tax) and I would like to add this into VersionKeeper workflow.

**Comment by adamgeorgeson** [comment]
Sorry I have only just spotted this. When do you need this by?

**Comment by bartoszpietras** [comment]
Hi, 
There is a change to this request, We just need to change CT Online to "Taxation online". As this holds two products now CT online and PT online and version number affects both applications.
Thanks,

Bart.

**Comment by adamgeorgeson** [comment]
Have actioned @bartoszpietras request on the box.
